<img src="https://sonal6789.github.io/images/profilepic.jpeg" width="150" height="150" align= "left"/> 

theme: jekyll-theme-cayman
title: SONAL CHAUDHARY
description: Screenshot of my work experience, projects and achievements
